## Setting up frequency of demand for ARIMA and SARIMAX

##For Hourly demand "H", "D" for daily,"W" for weekly, "M" for monthy 
resample_type:
  "H"

### from PMD AUTO ARIMA Tuning
sarima:
  order: [1, 1, 0]
  seasonal_order: [1, 0, 1, 24]
  enforce_stationarity: false
  enforce_invertibility: false

##only for XGBoost, used Optuna
best_params:
  n_estimators: 603
  max_depth: 3
  learning_rate: 0.19
  reg_alpha: 0.9
  reg_lambda: 0.64